apiVersion: v1
kind: Service
metadata:
  name: coder
  namespace: development
  labels:
    app: coder
spec:
  type: NodePort
  ports:
  - name: frontend
    nodePort: 32500
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: emberdevelopment
    nodePort: 32501
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
   app: coder